production:
  solr:
    hostname: localhost
    port: 8090
    log_level: WARNING
    path: /solr
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    hostname: localhost
    port: 8090
    log_level: WARNING
    path: /solr

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development
    solr_home: solr

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development
    solr_home: solr

